### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by cgvirus** [unfa/kdenlive-multirender#16]
Hi, as you have worked in this field for a good amount of time I want to verify if in your scenario this technique can be applied?
https://youtu.be/PytyNRd5R40

If it works then we can give KDENlive community a suggestion to include a simple button for this. For me everything is working as expected. 2 hrs of rendering took 20 mints.
Let me know. Thanks.

**Comment by unfa** [comment]
I am afraid this will not work. Frei0r effects are thread-unsafe - that's why Kdenlive can't use multiple CPU cores when using them. Trying to enforce that will most likely result in broken video files. However for me trying to enable multiple MLT threads breaks everything even when no Frei0r effects are used.
